language: python
python:
  - 2.6
  - 2.7
env:
  - PLONE_VERSION=4.1
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
matrix:
  exclude:
    - python: 2.7
      env: PLONE_VERSION=4.1
    - python: 2.6
      env: PLONE_VERSION=4.2
    - python: 2.6
      env: PLONE_VERSION=4.3
  allow_failures:
    - env: PLONE_VERSION=4.1
    - env: PLONE_VERSION=4.2
  fast_finish: true
addons:
  firefox: "34.0"
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - sed -ie "s#versions-$PLONE_VERSION.x#versions#" travis.cfg
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N -q
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - bin/code-analysis
  - bin/test
notifications:
  irc: irc.freenode.org#propertyshelf
